name: samthyang
favicon: null
layout_spectrum: 0.9546571641694754
typography_spectrum: 0.3518831040710211
title: samthyang
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2230514334514737
  lightness: 0.6663761022500694
  saturation: 0.5786579416599125
  rhythmicContrast: 0.7439363161101937
purpose: []
